name: changeset

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  changeset:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Setup | GitHub App
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup | Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup | Bun
        uses: ./.github/actions/setup-bun

      - name: Setup | Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .tool-versions

      - name: Run | Changeset
        uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          title: "chore(release): publish"
          commit: "chore(release): publish"
          version: bun run version-package
          publish: bun run release
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
